(function (window) {
    "use strict";

    var VMS = window.VMS = window.VMS || {};

    VMS.Constants = {
        DATASETS: [
            "ML_configuration", "Country", "City", "Currency", "Category",
            "userDB", "ML_vendor", "PR_PO", "PO_Lines", "Invoice",
            "Workflow_History", "SurveyQuestions", "Feedback_Assignment"
        ],
        ROLES: {
            SUPER_ADMIN: "SUPER_ADMIN",
            ADMIN: "ADMIN",
            UPPER_MANAGEMENT: "UPPER_MANAGEMENT",
            MANAGER: "MANAGER",
            EMPLOYEE: "EMPLOYEE",
            CO_OP: "CO_OP"
        },
        FUNCTIONS: {
            LFO_COMMERCIAL: "LFO_COMMERCIAL",
            LFO_MANUFACTURING: "LFO_MANUFACTURING",
            LFO_LEADERSHIP: "LFO_LEADERSHIP",
            EXCELLENCE: "EXCELLENCE",
            VENDOR_MANAGEMENT: "VENDOR_MANAGEMENT",
            EXECUTION: "EXECUTION",
            EDUCATION_PROGRAM: "EDUCATION_PROGRAM",
            ADMINISTRATION: "ADMINISTRATION"
        },
        ROUTES: {
            OVERVIEW: "OVERVIEW",
            VENDOR_LIST: "VENDOR_LIST",
            VENDOR_PROFILE: "VENDOR_PROFILE",
            PRPO_REGISTER: "PRPO_REGISTER",
            PRPO_APPROVAL: "PRPO_APPROVAL",
            PO_LINE_WORKSPACE: "PO_LINE_WORKSPACE",
            INVOICE_REGISTER: "INVOICE_REGISTER",
            INVOICE_PROCESSING: "INVOICE_PROCESSING",
            INVOICE_MANAGER_APPROVAL: "INVOICE_MANAGER_APPROVAL",
            CHARGEBACK_PROCESSING: "CHARGEBACK_PROCESSING",
            INVOICE_DETAILS: "INVOICE_DETAILS",
            FEEDBACK_ASSIGNMENTS: "FEEDBACK_ASSIGNMENTS",
            FEEDBACK_FORM: "FEEDBACK_FORM",
            REPORTS: "REPORTS",
            ADMINISTRATION: "ADMINISTRATION",
            PENDING_APPROVALS: "PENDING_APPROVALS",
            DIRECT_PAYMENT_REVIEW: "DIRECT_PAYMENT_REVIEW",
            DIRECT_PAYMENT_BATCH: "DIRECT_PAYMENT_BATCH"
        },
        INTERFACES: {
            OVERVIEW: "OVERVIEW",
            VENDOR_LIST: "VENDOR_LIST",
            VENDOR_ADD: "VENDOR_ADD",
            VENDOR_DOCUMENT_EVALUATION: "VENDOR_DOCUMENT_EVALUATION",
            VENDOR_INTERVIEW: "VENDOR_INTERVIEW",
            VENDOR_PROFILE_GENERAL: "VENDOR_PROFILE_GENERAL",
            VENDOR_PROFILE_DOCUMENTS: "VENDOR_PROFILE_DOCUMENTS",
            VENDOR_PROFILE_PRPO: "VENDOR_PROFILE_PRPO",
            VENDOR_PROFILE_INVOICES: "VENDOR_PROFILE_INVOICES",
            VENDOR_PROFILE_PERFORMANCE: "VENDOR_PROFILE_PERFORMANCE",
            VENDOR_ADMIN: "VENDOR_ADMIN",
            PRPO_REGISTER: "PRPO_REGISTER",
            PRPO_NEW: "PRPO_NEW",
            PRPO_APPROVAL: "PRPO_APPROVAL",
            PO_CREATE: "PO_CREATE",
            PO_LINE_WORKSPACE: "PO_LINE_WORKSPACE",
            PO_LINE_ADD_DETAILS: "PO_LINE_ADD_DETAILS",
            INVOICE_REGISTER: "INVOICE_REGISTER",
            INVOICE_ADD_EXECUTION: "INVOICE_ADD_EXECUTION",
            INVOICE_PROCESSING: "INVOICE_PROCESSING",
            INVOICE_MANAGER_APPROVAL: "INVOICE_MANAGER_APPROVAL",
            CHARGEBACK_PROCESSING: "CHARGEBACK_PROCESSING",
            INVOICE_DETAILS: "INVOICE_DETAILS",
            FEEDBACK_ASSIGNMENTS: "FEEDBACK_ASSIGNMENTS",
            FEEDBACK_FORM: "FEEDBACK_FORM",
            REPORTS: "REPORTS",
            ADMINISTRATION: "ADMINISTRATION",
            PENDING_APPROVALS: "PENDING_APPROVALS",
            DIRECT_PAYMENT_REVIEW: "DIRECT_PAYMENT_REVIEW",
            DIRECT_PAYMENT_BATCH: "DIRECT_PAYMENT_BATCH",
            INVOICE_ADD_EDUCATION_PROGRAM: "INVOICE_ADD_EDUCATION_PROGRAM",
            PRPO_ADMIN: "PRPO_ADMIN",
            INVOICE_ADMIN: "INVOICE_ADMIN"
        },
        VENDOR_STATES: {
            DOCUMENT_EVALUATION: "DOCUMENT_EVALUATION",
            INTERVIEW: "INTERVIEW",
            APPROVED: "APPROVED",
            REJECTED: "REJECTED",
            EXPIRED: "EXPIRED"
        },
        PRPO_STAGES: {
            MANAGER_REVIEW: "MANAGER_REVIEW",
            UPDATE_REQUIRED: "UPDATE_REQUIRED",
            PENDING_GPS: "PENDING_GPS",
            PO_ACTIVE: "PO_ACTIVE",
            REJECTED: "REJECTED"
        },
        PO_LINE_STAGES: {
            PLANNED: "PLANNED",
            CREATION: "CREATION",
            ACTIVE: "ACTIVE"
        },
        PO_LINE_STATUSES: {
            ACTIVE: "ACTIVE",
            THRESHOLD_REACHED: "THRESHOLD_REACHED",
            CONSUMED: "CONSUMED"
        },
        INVOICE_STAGES: {
            DIRECT_PAYMENT_REVIEW: "DIRECT_PAYMENT_REVIEW",
            PAYMENT_AGGREGATION: "PAYMENT_AGGREGATION",
            INVOICE_PROCESSING: "INVOICE_PROCESSING",
            PENDING_APPROVAL: "PENDING_APPROVAL",
            CHARGEBACK_PROCESSING: "CHARGEBACK_PROCESSING",
            SETTLED: "SETTLED",
            REJECTED: "REJECTED"
        },
        STATUSES: {
            PLANNED: "PLANNED",
            IN_PROGRESS: "IN_PROGRESS",
            APPROVED: "APPROVED",
            SETTLED: "SETTLED",
            REJECTED: "REJECTED",
            EXPIRED: "EXPIRED"
        },
        ERRORS: {
            ACCESS_DENIED: "ACCESS_DENIED",
            NOT_FOUND_OR_UNAUTHORIZED: "NOT_FOUND_OR_UNAUTHORIZED",
            INVALID_LINK: "INVALID_LINK",
            VALIDATION_FAILED: "VALIDATION_FAILED",
            DUPLICATE_KEY: "DUPLICATE_KEY",
            STALE_RECORD: "STALE_RECORD",
            INVALID_STAGE: "INVALID_STAGE",
            INSUFFICIENT_PO_BALANCE: "INSUFFICIENT_PO_BALANCE",
            BATCH_MEMBER_INVALID: "BATCH_MEMBER_INVALID",
            BATCH_LOCKED: "BATCH_LOCKED",
            CONFIGURATION_MISSING: "CONFIGURATION_MISSING",
            CONFIGURATION_INVALID: "CONFIGURATION_INVALID",
            ATTACHMENT_INVALID: "ATTACHMENT_INVALID",
            RECOVERY_REQUIRED: "RECOVERY_REQUIRED",
            SERVICE_UNAVAILABLE: "SERVICE_UNAVAILABLE",
            ACTION_OUTCOME_UNCERTAIN: "ACTION_OUTCOME_UNCERTAIN",
            UNSUPPORTED_OPERATION: "UNSUPPORTED_OPERATION"
        },
        WARNINGS: {
            EMAIL_FAILED_AFTER_COMMIT: "EMAIL_FAILED_AFTER_COMMIT"
        },
        ENTITY_TYPES: {
            VENDOR: "VENDOR",
            PR_PO: "PR_PO",
            PO_LINE: "PO_LINE",
            INVOICE: "INVOICE",
            DIRECT_PAYMENT_BATCH: "DIRECT_PAYMENT_BATCH",
            FEEDBACK: "FEEDBACK",
            FEEDBACK_ASSIGNMENT: "FEEDBACK_ASSIGNMENT",
            USER: "USER",
            CONFIG: "CONFIG",
            COUNTRY: "COUNTRY",
            CITY: "CITY",
            CURRENCY: "CURRENCY",
            CATEGORY: "CATEGORY",
            SURVEY_QUESTION: "SURVEY_QUESTION"
        },
        REPORT_SOURCES: ["VENDOR", "PRPO", "INVOICE", "USERDB", "SURVEY_QUESTION"],
        PO_LINE_NUMBERS: [10, 20, 30]
    };
}(window));

